package com.prince.secretsaccess;
import android.app.*;import android.os.*;import android.graphics.Color;import android.webkit.*;import android.widget.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.regex.*;
public class MainActivity extends Activity{
 static final String MANIFEST="https://raw.githubusercontent.com/divinegamingblogspot-dot/secret/main/media-manifest.jsonl";WebView web;
 public void onCreate(Bundle b){super.onCreate(b);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);TextView t=new TextView(this);t.setText("Secrets Access Prince");t.setTextSize(26);t.setTextColor(Color.rgb(210,40,100));t.setPadding(24,24,24,12);r.addView(t);web=new WebView(this);web.getSettings().setJavaScriptEnabled(false);web.getSettings().setMediaPlaybackRequiresUserGesture(true);r.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);load();}
 void load(){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(MANIFEST).openConnection();int z=c.getResponseCode();if(z!=200)throw new IOException("Manifest HTTP "+z);String d=read(c.getInputStream());c.disconnect();runOnUiThread(()->web.loadDataWithBaseURL("https://raw.githubusercontent.com/",html(d),"text/html","UTF-8",null));}catch(Exception e){runOnUiThread(()->web.loadData("<h2>Secrets Access</h2><p>"+esc(e.getMessage())+"</p>","text/html","UTF-8"));}}).start();}
 String html(String d){StringBuilder h=new StringBuilder("<html><head><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font-family:sans-serif;background:#111;color:#fff;padding:12px}.card{margin:12px 0;padding:12px;border-radius:18px;background:#222}.card img,.card video{width:100%;max-height:70vh;object-fit:contain;border-radius:14px}.slot{color:#ff6b9d;font-weight:bold}</style></head><body><h2>Authorized Secrets Media</h2>");for(String l:d.split("\\n")){String s=get(l,"slot"),n=get(l,"name"),u=get(l,"url"),type=get(l,"type");if(u.isEmpty())continue;h.append("<div class='card'><div class='slot'>").append(esc(s)).append("</div><div>").append(esc(n)).append("</div>");if(type.startsWith("video/"))h.append("<video controls preload='metadata' src='").append(attr(u)).append("'></video>");else h.append("<img loading='lazy' src='").append(attr(u)).append("'>");h.append("</div>");}return h.append("</body></html>").toString();}
 String get(String l,String k){Matcher m=Pattern.compile("\""+k+"\":\"((?:\\\\.|[^\"])*)\"").matcher(l);return m.find()?m.group(1).replace("\\\"","\""):"";}String esc(String s){return s==null?"":s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");}String attr(String s){return esc(s).replace(""","&quot;");}String read(InputStream in)throws Exception{try(BufferedReader b=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){StringBuilder s=new StringBuilder();String x;while((x=b.readLine())!=null)s.append(x).append('\\n');return s.toString();}}
}
